id = "logos-zed"
name = "Logos"
description = "Logos language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["tale"]
repository = "https://github.com/zwsn/logos-zed.git"
snippets = "./snippets/logos.json"

[language_servers.clangd]
name = "clangd"
languages = ["Logos"]

[language_servers.logos_language_server]
name = "Logos Language Server"
languages = ["Logos"]

[grammars.logos]
repository = "https://github.com/zwsn/logos-zed.git"
commit = "bd0d5aae129a8039583fb02b133c94e1d8ec2549"
path = "tree-sitter-logos"
