id = "logos-zed"
name = "Logos"
description = "Logos language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["tale"]
repository = "https://github.com/tale/logos-vscode"
snippets = "./snippets/logos.json"

[language_servers.clangd]
name = "clangd"
languages = ["Logos"]

[language_servers.logos_language_server]
name = "Logos Language Server"
languages = ["Logos"]

[grammars.logos]
repository = "file:///Users/h3r4/Desktop/logos-vscode/logos-zed"
commit = "fc47a896bffd71cced60dd0c3f9bf5b05aeebb8d"
path = "tree-sitter-logos"
