const directives = [
  {
    key: "ctor",
    label: "ctor",
    kind: 4,
    insertText: "ctor {\n\t${1}\n}",
    detail: "Constructor",
    documentation: [
      "#### Logos Constructor",
      "```",
      "%ctor {",
      "\t/* body */",
      "}",
      "```",
      "Generate an anonymous constructor (of default priority).",
      "This function is executed after the binary is loaded into memory.",
      "`argc`, `argv`, and `envp` are implicit arguments so they can be used as they would be in a `main` function.",
    ].join("\n"),
  },
  {
    key: "dtor",
    label: "dtor",
    kind: 4,
    insertText: "dtor {\n\t${1}\n}",
    detail: "Deconstructor",
    documentation: [
      "#### Logos Deconstructor",
      "```",
      "%dtor {",
      "\t/* body */",
      "}",
      "```",
      "Generate an anonymous deconstructor (of default priority).",
      "This function is executed before the binary is unloaded from memory.",
      "`argc`, `argv`, and `envp` are implicit arguments so they can be used as they would be in a `main` function.",
    ].join("\n"),
  },
  {
    key: "group",
    label: "group GroupName",
    kind: 3,
    insertText: "group ${1:GroupName}\n$0\n%end",
    detail: "Group",
    documentation: [
      "#### Logos Group",
      "```",
      "%group GroupName",
      "/* %hooks */",
      "%end",
      "```",
      "Generate a hook group with the name `GroupName`.",
      "Groups can be used for conditional initialization or code organization.",
      "All ungrouped hooks are in the default group, initializable via `%init` without arguments.",
      "Cannot be inside another `%group` block.",
    ].join("\n"),
  },
  {
    key: "hook",
    label: "hook HookName",
    kind: 3,
    insertText: "hook ${1:HookName}\n$0\n%end",
    detail: "Hook",
    documentation: [
      "### Logos Hook",
      "```",
      "%hook ClassName",
      "/* objc methods */",
      "%end",
      "```",
      "Open a hook block for the class named `ClassName`.",
      "Can be inside a `%group` block.",
    ].join("\n"),
  },
  {
    key: "new",
    label: "new",
    kind: 2,
    insertText: "new\n${1}",
    detail: "New",
    documentation: [
      "#### Logos New Method",
      "```",
      "%new",
      "/* objc method */",
      "```",
      "",
      "```",
      "%new(signature)",
      "/* objc method */",
      "```",
      "Add a new method to a hooked class or subclass by adding this directive above the method definition.",
      "`signature` is the Objective-C type encoding for the new method; if it is omitted, one will be generated.",
      "Must be inside a `%hook` or `%subclass` block.",
    ].join("\n"),
  },
  {
    key: "new",
    label: "new(signature)",
    kind: 2,
    insertText: "new(${1:signature})\n$0",
    detail: "New (Signature)",
    documentation: [
      "#### Logos New Method",
      "```",
      "%new",
      "/* objc method */",
      "```",
      "",
      "```",
      "%new(signature)",
      "/* objc method */",
      "```",
      "Add a new method to a hooked class or subclass by adding this directive above the method definition.",
      "`signature` is the Objective-C type encoding for the new method; if it is omitted, one will be generated.",
      "Must be inside a `%hook` or `%subclass` block.",
    ].join("\n"),
  },
  {
    key: "subclass",
    label: "subclass ClassName : SuperClass",
    kind: 7,
    insertText: "subclass ${1:ClassName} : ${2:SuperClass}\n$0\n%end",
    detail: "Subclass",
    documentation: [
      "#### Logos Subclass",
      "```",
      "%subclass ClassName: Superclass <Protocol list>",
      "/* %properties and methods */",
      "%end",
      "```",
      "Generate a subclass at runtime.",
      "Like `@property` in normal Objective-C classes, you can use `%property` to add properties to the subclass.",
      "The `%new` specifier is needed for a method that does not exist in the superclass.",
    ].join("\n"),
  },
  {
    key: "property",
    label: "property (attributes...) Type name",
    kind: 10,
    insertText: "property (${1:attributes...}) ${2:Type} ${0:name}",
    detail: "Property",
    documentation: [
      "#### Logos Property",
      "```",
      "%property (nonatomic|assign|retain|copy|weak|strong|getter=...|setter=...) Type name;",
      "```",
      "Add a property to a `%subclass` just like you would with `@property` in normal Objective-C,",
      "and add new properties to existing classes within `%hook`.",
      "Must be inside a `%hook` or `%subclass` block.",
    ].join("\n"),
  },
  {
    key: "init",
    label: "init",
    kind: 24,
    insertText: "init;",
    detail: "Init",
    documentation: [
      "#### Logos Init",
      "```",
      "%init;",
      "```",
      "",
      "```",
      "%init([<ClassName>=<expr>, ...]);",
      "```",
      "",
      "```",
      "%init(GroupName[, [+|-]<ClassName>=<expr>, ...]);",
      "```",
      "Initialize a group's method and function hooks.",
    ].join("\n"),
  },
  {
    key: "init",
    label: "init([...])",
    kind: 24,
    insertText: "init([${1:ClassName}=${2:expr}, ${0:...}]);",
    detail: "Init (Arguments)",
    documentation: [
      "#### Logos Init",
      "```",
      "%init;",
      "```",
      "",
      "```",
      "%init([<ClassName>=<expr>, ...]);",
      "```",
      "",
      "```",
      "%init(GroupName[, [+|-]<ClassName>=<expr>, ...]);",
      "```",
      "Initialize a group's method and function hooks.",
    ].join("\n"),
  },
  {
    key: "init",
    label: "init([[+|-], ...])",
    kind: 24,
    insertText:
      "init(${1:GroupName}[, [${2:+|-}]${3:ClassName}=${4:expr}, ${0:...}]);",
    detail: "Init (Arguments)",
    documentation: [
      "#### Logos Init",
      "```",
      "%init;",
      "```",
      "",
      "```",
      "%init([<ClassName>=<expr>, ...]);",
      "```",
      "",
      "```",
      "%init(GroupName[, [+|-]<ClassName>=<expr>, ...]);",
      "```",
      "Initialize a group's method and function hooks.",
    ].join("\n"),
  },
  {
    key: "c",
    label: "c()",
    kind: 24,
    insertText: "c(${1:ClassName})",
    detail: "Class",
    documentation: [
      "#### Logos Class",
      "```",
      "%c([+|-]ClassName)",
      "```",
      "Evaluates to `ClassName` at runtime.",
      "If the `+` sigil is specified, it evaluates to MetaClass instead of Class.",
    ].join("\n"),
  },
  {
    key: "orig",
    label: "orig",
    kind: 24,
    insertText: "orig",
    detail: "Orig",
    documentation: [
      "#### Logos Orig",
      "```",
      "%orig",
      "```",
      "",
      "```",
      "%orig(args, ...)",
      "```",
      "Call the original hooked function or method.",
      "Does not work in a `%new` method.",
    ].join("\n"),
  },
  {
    key: "orig",
    label: "orig()",
    kind: 24,
    insertText: "orig(${1:args...})",
    detail: "Orig (Arguments)",
    documentation: [
      "#### Logos Orig",
      "```",
      "%orig",
      "```",
      "",
      "```",
      "%orig(args, ...)",
      "```",
      "Call the original hooked function or method.",
      "Does not work in a `%new` method.",
    ].join("\n"),
  },
  {
    key: "log",
    label: "log",
    kind: 24,
    insertText: "log",
    detail: "Log",
    documentation: [
      "#### Logos Log",
      "```",
      "%log;",
      "```",
      "",
      "```",
      "%log([(<type>)<expr>, ...]);",
      "```",
      "Dump the method arguments to syslog.",
      "Typed arguments included in `%log` will be logged as well.",
    ].join("\n"),
  },
  {
    key: "log",
    label: "log()",
    kind: 24,
    insertText: "log(${1:args...})",
    detail: "Log (Arguments)",
    documentation: [
      "#### Logos Log",
      "```",
      "%log;",
      "```",
      "",
      "```",
      "%log([(<type>)<expr>, ...]);",
      "```",
      "Dump the method arguments to syslog.",
      "Typed arguments included in `%log` will be logged as well.",
    ].join("\n"),
  },
];

const hoverByKey = new Map([
  [
    "end",
    [
      "#### Logos End Directive",
      "```",
      "%end",
      "```",
      "Close a `%group`, `%hook` or `%subclass` block.",
    ].join("\n"),
  ],
]);

for (const directive of directives) {
  if (!hoverByKey.has(directive.key)) {
    hoverByKey.set(directive.key, directive.documentation);
  }
}

module.exports = {
  directives,
  hoverByKey,
};
