; inherits: c

[
  (logos_hook_block)
  (logos_group_block)
  (logos_subclass_block)
  (logos_ctor_definition)
  (logos_dtor_definition)
  (class_declaration)
  (class_interface)
  (class_implementation)
  (protocol_declaration)
  (property_declaration)
  (method_declaration)
  (struct_declaration)
  (struct_declarator)
  (try_statement)
  (catch_clause)
  (finally_clause)
  (throw_statement)
  (block_literal)
  (ms_asm_block)
  (dictionary_literal)
  (array_literal)
] @fold
